"""add pro_expires_at to users

Revision ID: 55652a97a7ca
Revises: b9adaf9f3555
Create Date: 2026-06-07 11:30:18.194414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55652a97a7ca'
down_revision: Union[str, Sequence[str], None] = 'b9adaf9f3555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pro_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pro_expires_at')
    # ### end Alembic commands ###
