"""add payment fields

Revision ID: ec05e564beec
Revises: 55652a97a7ca
Create Date: 2026-06-08 17:54:15.221605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec05e564beec'
down_revision: Union[str, Sequence[str], None] = '55652a97a7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('pro_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pro_expires_at')
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###
